"""Added Academic Structure

Revision ID: f4aad55634de
Revises: 12e95578a229
Create Date: 2026-06-17 17:05:13.923411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4aad55634de'
down_revision = '12e95578a229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_sessions_level_id', 'levels', ['level_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! -> ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sessions_level_id', type_='foreignkey')
        batch_op.drop_column('level_id')

    op.drop_table('levels')
    # ### end Alembic commands ###
